#!/bin/sh

packages=('android-a52dec a52dec'
          'android-abseil-cpp abseil-cpp'
          'android-alsa-lib alsa-lib'
          'android-alsa-topology-conf alsa-topology-conf'
          'android-alsa-ucm-conf alsa-ucm-conf'
          'android-aom aom'
          'android-argparse argparse'
          'android-avisynthplus avisynthplus'
          'android-boost boost'
          'android-brotli brotli'
          'android-bzip2 bzip2'
          'android-cairo cairo'
          'android-cairo-bootstrap cairo'
          'android-cdparanoia cdparanoia'
          'android-cmocka cmocka'
          'android-cracklib cracklib'
          'android-curl curl'
          'android-dav1d dav1d'
          'android-devil devil'
          'android-eigen eigen'
          'android-expat expat'
          'android-faac faac'
          'android-ffmpeg ffmpeg'
          'android-fftw fftw'
          'android-flac flac'
          'android-fmt fmt'
          'android-fontconfig fontconfig'
          'android-freetype2 freetype2'
          'android-freetype2-bootstrap freetype2'
          'android-fribidi fribidi'
          'android-gavl gavl'
          'android-gdbm gdbm'
          'android-gdk-pixbuf2 gdk-pixbuf2'
          'android-gdk-pixbuf2-bootstrap gdk-pixbuf2'
          'android-gettext gettext'
          'android-giflib giflib'
          'android-glib2 glib2'
          'android-gmp gmp'
          'android-gnutls gnutls'
          'android-gpgme gpgme'
          'android-graphite graphite'
          'android-gsm gsm'
          'android-gtest gtest'
          'android-harfbuzz harfbuzz'
          'android-hidapi hidapi'
          'android-highway highway'
          'android-hwdata hwdata'
          'android-hwloc hwloc'
          'android-icu icu'
          'android-imath imath'
          'android-jasper jasper'
          'android-jbigkit jbigkit'
          'android-jemalloc jemalloc'
          'android-json-c json-c'
          'android-judy judy'
          'android-kmod kmod'
          'android-l-smash l-smash'
          'android-ladspa ladspa'
          'android-lame lame'
          'android-lcms2 lcms2'
          'android-libarchive libarchive'
          'android-libass libass'
          'android-libassuan libassuan'
          'android-libasyncns libasyncns'
          'android-libavc1394 libavc1394'
          'android-libavif libavif'
          'android-libbluray libbluray'
          'android-libbs2b libbs2b'
          'android-libcap-ng libcap-ng'
          'android-libcdio libcdio'
          'android-libdatrie libdatrie'
          'android-libdc1394 libdc1394'
          'android-libde265 libde265'
          'android-libdeflate libdeflate'
          'android-libdovi libdovi'
          'android-libdrm libdrm'
          'android-libdv libdv'
          'android-libdvdcss libdvdcss'
          'android-libdvdread libdvdread'
          'android-libebml libebml'
          'android-libevent libevent'
          'android-libfabric libfabric'
          'android-libffi libffi'
          'android-libgcrypt libgcrypt'
          'android-libgpg-error libgpg-error'
          'android-libheif libheif'
          'android-libheif-bootstrap libheif'
          'android-libice libice'
          'android-libiconv libiconv'
          'android-libidn2 libidn2'
          'android-libiec61883 libiec61883'
          'android-libjpeg-turbo libjpeg-turbo'
          'android-libjxl libjxl'
          'android-libksba libksba'
          'android-libmatroska libmatroska'
          'android-libmicrohttpd libmicrohttpd'
          'android-libmodplug libmodplug'
          'android-libmp4v2 libmp4v2'
          'android-libmpeg2 libmpeg2'
          'android-libnghttp2 libnghttp2'
          'android-libnghttp3 libnghttp3'
          'android-libnl libnl'
          'android-libogg libogg'
          'android-libopenmpt libopenmpt'
          'android-libpciaccess libpciaccess'
          'android-libpng libpng'
          'android-libpsl libpsl'
          'android-libraw1394 libraw1394'
          'android-librsvg librsvg'
          'android-libsamplerate libsamplerate'
          'android-libsasl libsasl'
          'android-libsasl-bootstrap libsasl'
          'android-libshout libshout'
          'android-libsm libsm'
          'android-libsndfile libsndfile'
          'android-libsodium libsodium'
          'android-libsoup3 libsoup3'
          'android-libsoxr libsoxr'
          'android-libssh libssh'
          'android-libssh2 libssh2'
          'android-libtasn1 libtasn1'
          'android-libthai libthai'
          'android-libtheora libtheora'
          'android-libtiff libtiff'
          'android-libtool libtool'
          'android-libtpms libtpms'
          'android-libunibreak libunibreak'
          'android-libunistring libunistring'
          'android-liburing liburing'
          'android-libusb libusb'
          'android-libuvc libuvc'
          'android-libva libva'
          'android-libvdpau libvdpau'
          'android-libvorbis libvorbis'
          'android-libvpl libvpl'
          'android-libvpx libvpx'
          'android-libwebm libwebm'
          'android-libwebp libwebp'
          'android-libwmf libwmf'
          'android-libx11 libx11'
          'android-libxau libxau'
          'android-libxcb libxcb'
          'android-libxcrypt libxcrypt'
          'android-libxcursor libxcursor'
          'android-libxdamage libxdamage'
          'android-libxdmcp libxdmcp'
          'android-libxext libxext'
          'android-libxfixes libxfixes'
          'android-libxft libxft'
          'android-libxi libxi'
          'android-libxinerama libxinerama'
          'android-libxkbcommon libxkbcommon'
          'android-libxml2 libxml2'
          'android-libxmu libxmu'
          'android-libxrandr libxrandr'
          'android-libxrender libxrender'
          'android-libxslt libxslt'
          'android-libxss libxss'
          'android-libxt libxt'
          'android-libxtst libxtst'
          'android-libxv libxv'
          'android-libyuv libyuv'
          'android-lv2 lv2'
          'android-lz4 lz4'
          'android-lzo lzo'
          'android-mariadb mariadb'
          'android-mpfr mpfr'
          'android-mpg123 mpg123'
          'android-ncurses ncurses'
          'android-nettle nettle'
          'android-npth npth'
          'android-nspr nspr'
          'android-nss nss'
          'android-numactl numactl'
          'android-ocl-icd ocl-icd'
          'android-onetbb onetbb'
          'android-opencl-clhpp opencl-clhpp'
          'android-opencl-headers opencl-headers'
          'android-opencore-amr opencore-amr'
          'android-openexr openexr'
          'android-openjpeg2 openjpeg2'
          'android-openldap libldap'
          'android-openmpi openmpi'
          'android-openpmix openpmix'
          'android-openssl openssl'
          'android-opentimelineio opentimelineio'
          'android-opus opus'
          'android-p11-kit p11-kit'
          'android-pango pango'
          'android-pciutils pciutils'
          'android-pcre pcre'
          'android-pcre2 pcre2'
          'android-pcsclite pcsclite'
          'android-pixman pixman'
          'android-pocl pocl'
          'android-poppler poppler'
          'android-poppler-data poppler-data'
          'android-popt popt'
          'android-portaudio portaudio'
          'android-postgresql postgresql'
          'android-prrte prrte'
          'android-rav1e rav1e'
          'android-readline readline'
          'android-rubberband rubberband'
          'android-sdl2 sdl2'
          'android-serd serd'
          'android-snappy snappy'
          'android-sord sord'
          'android-speex speex'
          'android-speexdsp speexdsp'
          'android-sqlite sqlite'
          'android-srt srt'
          'android-svt-av1 svt-av1'
          'android-taglib taglib'
          'android-tcl tcl'
          'android-termcap termcap'
          'android-tpm2-tss tpm2-tss'
          'android-twolame twolame'
          'android-unixodbc unixodbc'
          'android-utf8cpp utf8cpp'
          'android-vamp-plugin-sdk vamp-plugin-sdk'
          'android-vapoursynth vapoursynth'
          'android-verdict verdict'
          'android-vid.stab vid.stab'
          'android-vmaf vmaf'
          'android-wavpack wavpack'
          'android-webp-pixbuf-loader webp-pixbuf-loader'
          'android-webrtc-audio-processing-1 webrtc-audio-processing-1'
          'android-x264 x264'
          'android-x264-bootstrap x264'
          'android-x265 x265'
          'android-xcb-proto xcb-proto'
          'android-xkeyboard-config xkeyboard-config'
          'android-xorg-util-macros xorg-util-macros'
          'android-xorgproto xorgproto'
          'android-xtrans xtrans'
          'android-xvidcore xvidcore'
          'android-xxhash xxhash'
          'android-xz xz'
          'android-zimg zimg'
          'android-zix zix'
          'android-zlib zlib'
          'android-zstd zstd'
          'weblate-wlc weblate-wlc')

export LC_ALL=C

for package in "${packages[@]}"; do
    pkg=$(echo $package | awk '{print $1}')
    pkgbuild="${PWD}/${pkg}/PKGBUILD"

    if [ ! -e "${pkgbuild}" ]; then
        echo -e "$pkg \e[31mmissing\e[0m"

        continue
    fi

    lines=$(grep -n 'build() {' "${pkgbuild}" | awk -F: '{print $1}')
    lines=$(echo "${lines} - 1" | bc)
    pkgBuildLines=$(head -n "${lines}" "${pkgbuild}")
    pkgverLine="${pkgBuildLines};"$'\n'"echo \${pkgver}"
    pkg_ver=$(echo "${pkgverLine}" | sh)
    pkg_orig=$(echo $package | awk '{print $2}')
    pkg_info=$(pacman -Si $pkg_orig 2>/dev/null)

    if [ "$?" = 0 ]; then
        pkg_orig_ver=$(echo "${pkg_info}" | grep 'Version\s*:' | awk '{print $3}' | cut -d "-" -f1 | cut -d ":" -f2)
        pkg_orig_ver=${pkg_orig_ver%%+*}
        older_ver=$(printf "${pkg_ver}\n${pkg_orig_ver}" | sort -V | head -n 1)

        if [ "${older_ver}" = "${pkg_orig_ver}" ]; then
            echo -e "$pkg \e[32m$pkg_ver\e[0m"
        else
            echo -e "$pkg \e[31m$pkg_ver -> ${pkg_orig_ver}\e[0m"
        fi
    else
        echo -e "$pkg \e[33m$pkg_ver !\e[0m"
    fi
done
